### ISSUE TITLE
Can’t update island info

### ISSUE THREAD

**Issue by utopiatabitha** [fpedro23/acnh-connect-issues#1]
When I try to edit island it only shows the dialog box to type about island and won’t let me select visitors to island or anything or save

**Comment by fpedro23** [comment]
Hi there, thank you so much for the feedback. Yes, that is an issue we’re working on solving. It should be resolved soon. In the meantime, there is a little trick to get around it - when you open the edit screen, drag your finger from the bottom up (under the fruit section). It should allow you to edit the profile. We know that’s not a permanent solution, but at least for now you can edit your island. Thanks again! Please let us know if you find any other problems.

**Comment by utopiatabitha** [comment]
Thank you!!

**Comment by fpedro23** [comment]
Fixed in 1.1.1 (36).
