### ISSUE TITLE
Very buggy app

### ISSUE THREAD

**Issue by JVHazard** [fpedro23/acnh-connect-issues#2]
So basically when I tap on “Islands”, nothing shows up. All I see is the top part and a white screen. Secondly, it says that I can post multiple pictures, but I can only post one. This app is just really buggy overall and it would be great if it were to be fixed.

**Comment by fpedro23** [comment]
Hello JVHazard! Can you send us a screenshot of the problem? We’ll be releasing a fix this weekend to address all the island edition issues we’ve got.

**Comment by JVHazard** [comment]
![0ABBB160-BB61-4519-BD9B-AC339F8AC526](https://user-images.githubusercontent.com/67183512/85212107-e4983980-b392-11ea-9468-2a9baf4ffac0.png)
![Uploading C1BFD902-BECE-4CA6-B8AE-7D3648ED3AB8.png…]()

**Comment by fpedro23** [comment]
First time I see this issue. What is your device and iOS version? Did you download the latest version of thw app store?

**Comment by JVHazard** [comment]
6S and 1.1.0

**Comment by JVHazard** [comment]
Oh hang on, never mind. I updated my phone and it works now
